<html>
<head>
    <link rel="stylesheet" type="text/css" href="blog.css">
</head>
<body>
<body id="body">
<div id="head">
    <h1 onclick="location.href='../Paginaciones/Paginacion_home/index.php'">InfoTeach</h1>


</div>

<div id="options">
    <link rel="stylesheet" type="text/css" href="panel.css">
    <a href="publicar/publicar.html" class="myButton">Publicar</a>
    <br>
    <a href="#" class="myButton">Editar</a>
    <br>
    <a href="delete/delete.phtml" class="myButton">Borrar</a>
</div>


</div>
</body>
</html>
<?php
$conexion = new PDO('mysql:host=fmesasc.com;dbname=daw2', 'daw2', 'Gimbernat');

