<head>
    <title>InfoTeach</title>
</head>
<body id="body">
<div id="head">
    <h1>InfoTeach</h1>
    <div id="options">
        <link rel="stylesheet" type="text/css" href="panel.css">
        <a href="https://google.es" class="myButton">Publicar</a>
        <br>
        <a href="#" class="myButton">Editar</a>

        <a href="#" class="myButton">Borrar</a>
    </div>

</body>
</html>
<?php
$conexion = new PDO('mysql:host=fmesasc.com;dbname=daw2', 'daw2', 'Gimbernat');

