<?php
$conexion = new PDO('mysql:host=fmesasc.com;dbname=daw2', 'daw2', 'Gimbernat');
session_start();


$result = $conexion->query('SELECT title,description,content,image,date FROM web_grupo_alex_foro WHERE title="' . $_POST['title'] . '"')->fetch();
?>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="blog.css">
</head>
<body>
<body id="body">
<div id="head">
    <h1 onclick="location.href='../Paginaciones/Paginacion_home/index.php'">InfoTeach</h1>


</div>

<h1><?php echo $result['title'] ?></h1>

<div id="content_blog">
    <div id="description"></div>
    <a><?php echo $result['description'] ?></a>
    <br>
    <div id="content"></div>
    <a><?php echo $result['content'] ?></a>
    <br>
    <div id="image"></div>
    <a><img src="<?php echo "../../images/" . $result['image']; ?>" alt="<?php echo $result['title']; ?>"
            width="400" height="350">
    </a>
    <br>
    <div id="date"></div>
    <a><?php echo $result['date'] ?></a>
    <br>
</div>
<div id="comentarios">
<h2>Comentarios</h2>
    <?php
$resulta = $conexion->query('SELECT * FROM web_grupo_alex_comentario where post ="' .$result['title']  . '"');
foreach ($resulta as $fila) {
    echo $fila['user'];
    ?>
    <a> a las</a>
    <?php
    echo $fila['date'] ;
    ?>
    <a> dice :</a>
    <?php
    echo $fila['content'] . '</br>';
echo '</br>';
}
?>
<form action="comentarios/comentarios.phtml" method="post" id="boton">
    <input type="hidden" name="title" value="<?php echo $result['title'] ?>">
    <input id="boton" type="submit" value="Publicar comentario">
</form>


</div>
</div>
</body>
</html>