
<?php
session_start();
if (isset($_SESSION['user'])) {
?>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="delete.css">
</head>

<body id="body">
<div id="head">
    <h1 onclick="location.href='../../Paginaciones/Paginacion_home/index.php'">InfoTeach</h1>


</div>
<?php
$conexion = new PDO('mysql:host=fmesasc.com;dbname=daw2', 'daw2', 'Gimbernat');
$resulta = $conexion->query("SELECT * FROM web_grupo_alex_foro ");
foreach ($resulta as $fila) {
    echo $fila['title'] . '</br>';
    ?>
    <form action="delete.php" method="post">
        <input type="hidden" name="title" value="<?php echo $fila['title'] ?>">
        <input type="submit" value="borrar post">
    </form>
    <?php
}
?>



</div>
<?php
}else{
    echo "NO ERES ADMIN";
}
?>
</body>
</html>
