<?php
$show_botton = "yes";
?>
<div class="container">
<h1>Bienvenido!</h1>

    <link rel="stylesheet" type="text/css" href="login_sign_up.css">

        <button onclick="window.location.href='login/login.html';">
            Login
        </button>
        <button onclick="window.location.href='sign_up/sign_up.phtml';">
            Sign up
        </button>

    </a>

    <div class="pass-link">

    </div>
</div>